/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InferenceRequest
 */
export interface InferenceRequest {
    /**
     * 
     * @type {number}
     * @memberof InferenceRequest
     */
    shopId: number;
    /**
     * 
     * @type {boolean}
     * @memberof InferenceRequest
     */
    shouldDetectBarcode?: boolean;
    /**
     * 
     * @type {Blob}
     * @memberof InferenceRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the InferenceRequest interface.
 */
export function instanceOfInferenceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "shopId" in value;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function InferenceRequestFromJSON(json: any): InferenceRequest {
    return InferenceRequestFromJSONTyped(json, false);
}

export function InferenceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InferenceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shopId': json['shop_id'],
        'shouldDetectBarcode': !exists(json, 'shouldDetectBarcode') ? undefined : json['shouldDetectBarcode'],
        'file': json['file'],
    };
}

export function InferenceRequestToJSON(value?: InferenceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shop_id': value.shopId,
        'shouldDetectBarcode': value.shouldDetectBarcode,
        'file': value.file,
    };
}

