/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddBarcodeRequest
 */
export interface AddBarcodeRequest {
    /**
     * 
     * @type {string}
     * @memberof AddBarcodeRequest
     */
    value: string;
    /**
     * 
     * @type {number}
     * @memberof AddBarcodeRequest
     */
    itemId: number;
}

/**
 * Check if a given object implements the AddBarcodeRequest interface.
 */
export function instanceOfAddBarcodeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "itemId" in value;

    return isInstance;
}

export function AddBarcodeRequestFromJSON(json: any): AddBarcodeRequest {
    return AddBarcodeRequestFromJSONTyped(json, false);
}

export function AddBarcodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddBarcodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'itemId': json['item_id'],
    };
}

export function AddBarcodeRequestToJSON(value?: AddBarcodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'item_id': value.itemId,
    };
}

