/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddItemTypeRequest
 */
export interface AddItemTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof AddItemTypeRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AddItemTypeRequest
     */
    basePrice: number;
    /**
     * 
     * @type {number}
     * @memberof AddItemTypeRequest
     */
    retail: number;
}

/**
 * Check if a given object implements the AddItemTypeRequest interface.
 */
export function instanceOfAddItemTypeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "basePrice" in value;
    isInstance = isInstance && "retail" in value;

    return isInstance;
}

export function AddItemTypeRequestFromJSON(json: any): AddItemTypeRequest {
    return AddItemTypeRequestFromJSONTyped(json, false);
}

export function AddItemTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddItemTypeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'basePrice': json['base_price'],
        'retail': json['retail'],
    };
}

export function AddItemTypeRequestToJSON(value?: AddItemTypeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'base_price': value.basePrice,
        'retail': value.retail,
    };
}

