/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeductDepositRequest
 */
export interface DeductDepositRequest {
    /**
     * 
     * @type {number}
     * @memberof DeductDepositRequest
     */
    targetId: number;
    /**
     * 
     * @type {number}
     * @memberof DeductDepositRequest
     */
    amount: number;
}

/**
 * Check if a given object implements the DeductDepositRequest interface.
 */
export function instanceOfDeductDepositRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "targetId" in value;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function DeductDepositRequestFromJSON(json: any): DeductDepositRequest {
    return DeductDepositRequestFromJSONTyped(json, false);
}

export function DeductDepositRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeductDepositRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'targetId': json['target_id'],
        'amount': json['amount'],
    };
}

export function DeductDepositRequestToJSON(value?: DeductDepositRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'target_id': value.targetId,
        'amount': value.amount,
    };
}

