/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ItemRequest } from './ItemRequest';
import {
    ItemRequestFromJSON,
    ItemRequestFromJSONTyped,
    ItemRequestToJSON,
} from './ItemRequest';

/**
 * 
 * @export
 * @interface EditItemRequest
 */
export interface EditItemRequest {
    /**
     * 
     * @type {Array<ItemRequest>}
     * @memberof EditItemRequest
     */
    items: Array<ItemRequest>;
    /**
     * 
     * @type {number}
     * @memberof EditItemRequest
     */
    shopId: number;
}

/**
 * Check if a given object implements the EditItemRequest interface.
 */
export function instanceOfEditItemRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "shopId" in value;

    return isInstance;
}

export function EditItemRequestFromJSON(json: any): EditItemRequest {
    return EditItemRequestFromJSONTyped(json, false);
}

export function EditItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditItemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ItemRequestFromJSON)),
        'shopId': json['shop_id'],
    };
}

export function EditItemRequestToJSON(value?: EditItemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(ItemRequestToJSON)),
        'shop_id': value.shopId,
    };
}

