/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditAuthRequest
 */
export interface EditAuthRequest {
    /**
     * 
     * @type {number}
     * @memberof EditAuthRequest
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EditAuthRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof EditAuthRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof EditAuthRequest
     */
    confirmPassword: string;
    /**
     * 
     * @type {string}
     * @memberof EditAuthRequest
     */
    email: string;
}

/**
 * Check if a given object implements the EditAuthRequest interface.
 */
export function instanceOfEditAuthRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "confirmPassword" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function EditAuthRequestFromJSON(json: any): EditAuthRequest {
    return EditAuthRequestFromJSONTyped(json, false);
}

export function EditAuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditAuthRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'password': json['password'],
        'confirmPassword': json['confirm_password'],
        'email': json['email'],
    };
}

export function EditAuthRequestToJSON(value?: EditAuthRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
        'password': value.password,
        'confirm_password': value.confirmPassword,
        'email': value.email,
    };
}

