/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditClientRequest
 */
export interface EditClientRequest {
    /**
     * 
     * @type {number}
     * @memberof EditClientRequest
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EditClientRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EditClientRequest
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof EditClientRequest
     */
    phoneNumber: string;
}

/**
 * Check if a given object implements the EditClientRequest interface.
 */
export function instanceOfEditClientRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "phoneNumber" in value;

    return isInstance;
}

export function EditClientRequestFromJSON(json: any): EditClientRequest {
    return EditClientRequestFromJSONTyped(json, false);
}

export function EditClientRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditClientRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'phoneNumber': json['phone_number'],
    };
}

export function EditClientRequestToJSON(value?: EditClientRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'gender': value.gender,
        'phone_number': value.phoneNumber,
    };
}

