/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InferenceResult
 */
export interface InferenceResult {
    /**
     * 
     * @type {Array<object>}
     * @memberof InferenceResult
     */
    items: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof InferenceResult
     */
    totalPrice: number;
    /**
     * 
     * @type {number}
     * @memberof InferenceResult
     */
    totalItems: number;
}

/**
 * Check if a given object implements the InferenceResult interface.
 */
export function instanceOfInferenceResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "totalPrice" in value;
    isInstance = isInstance && "totalItems" in value;

    return isInstance;
}

export function InferenceResultFromJSON(json: any): InferenceResult {
    return InferenceResultFromJSONTyped(json, false);
}

export function InferenceResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): InferenceResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': json['items'],
        'totalPrice': json['totalPrice'],
        'totalItems': json['totalItems'],
    };
}

export function InferenceResultToJSON(value?: InferenceResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items,
        'totalPrice': value.totalPrice,
        'totalItems': value.totalItems,
    };
}

