/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PendingTopupTransactionRequest
 */
export interface PendingTopupTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof PendingTopupTransactionRequest
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof PendingTopupTransactionRequest
     */
    cashierlessAccountNumber: string;
    /**
     * 
     * @type {number}
     * @memberof PendingTopupTransactionRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof PendingTopupTransactionRequest
     */
    transactionId: string;
    /**
     * 
     * @type {string}
     * @memberof PendingTopupTransactionRequest
     */
    transactionDateandTime: string;
    /**
     * 
     * @type {string}
     * @memberof PendingTopupTransactionRequest
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PendingTopupTransactionRequest
     */
    status: string;
}

/**
 * Check if a given object implements the PendingTopupTransactionRequest interface.
 */
export function instanceOfPendingTopupTransactionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "cashierlessAccountNumber" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "transactionId" in value;
    isInstance = isInstance && "transactionDateandTime" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function PendingTopupTransactionRequestFromJSON(json: any): PendingTopupTransactionRequest {
    return PendingTopupTransactionRequestFromJSONTyped(json, false);
}

export function PendingTopupTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingTopupTransactionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'cashierlessAccountNumber': json['cashierless_account_number'],
        'amount': json['amount'],
        'transactionId': json['transactionId'],
        'transactionDateandTime': json['transactionDateandTime'],
        'currencyCode': !exists(json, 'currencyCode') ? undefined : json['currencyCode'],
        'status': json['status'],
    };
}

export function PendingTopupTransactionRequestToJSON(value?: PendingTopupTransactionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client_id': value.clientId,
        'cashierless_account_number': value.cashierlessAccountNumber,
        'amount': value.amount,
        'transactionId': value.transactionId,
        'transactionDateandTime': value.transactionDateandTime,
        'currencyCode': value.currencyCode,
        'status': value.status,
    };
}

