/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendFileRequest
 */
export interface SendFileRequest {
    /**
     * 
     * @type {string}
     * @memberof SendFileRequest
     */
    file: string;
}

/**
 * Check if a given object implements the SendFileRequest interface.
 */
export function instanceOfSendFileRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function SendFileRequestFromJSON(json: any): SendFileRequest {
    return SendFileRequestFromJSONTyped(json, false);
}

export function SendFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendFileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function SendFileRequestToJSON(value?: SendFileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

