/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpWithShopRequest
 */
export interface SignUpWithShopRequest {
    /**
     * 
     * @type {string}
     * @memberof SignUpWithShopRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithShopRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithShopRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithShopRequest
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof SignUpWithShopRequest
     */
    isShopOwner?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithShopRequest
     */
    gender?: string;
    /**
     * 
     * @type {Date}
     * @memberof SignUpWithShopRequest
     */
    birthdate?: Date;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithShopRequest
     */
    phoneNumber: string;
    /**
     * 
     * @type {Blob}
     * @memberof SignUpWithShopRequest
     */
    faceImg?: Blob;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithShopRequest
     */
    profileImg?: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithShopRequest
     */
    shopName: string;
    /**
     * 
     * @type {number}
     * @memberof SignUpWithShopRequest
     */
    machineId: number;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithShopRequest
     */
    shopPhoneNumber: string;
}

/**
 * Check if a given object implements the SignUpWithShopRequest interface.
 */
export function instanceOfSignUpWithShopRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "phoneNumber" in value;
    isInstance = isInstance && "shopName" in value;
    isInstance = isInstance && "machineId" in value;
    isInstance = isInstance && "shopPhoneNumber" in value;

    return isInstance;
}

export function SignUpWithShopRequestFromJSON(json: any): SignUpWithShopRequest {
    return SignUpWithShopRequestFromJSONTyped(json, false);
}

export function SignUpWithShopRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpWithShopRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'email': json['email'],
        'name': json['name'],
        'isShopOwner': !exists(json, 'is_shop_owner') ? undefined : json['is_shop_owner'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'birthdate': !exists(json, 'birthdate') ? undefined : (new Date(json['birthdate'])),
        'phoneNumber': json['phone_number'],
        'faceImg': !exists(json, 'face_img') ? undefined : json['face_img'],
        'profileImg': !exists(json, 'profile_img') ? undefined : json['profile_img'],
        'shopName': json['shop_name'],
        'machineId': json['machine_id'],
        'shopPhoneNumber': json['shop_phone_number'],
    };
}

export function SignUpWithShopRequestToJSON(value?: SignUpWithShopRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'email': value.email,
        'name': value.name,
        'is_shop_owner': value.isShopOwner,
        'gender': value.gender,
        'birthdate': value.birthdate === undefined ? undefined : (value.birthdate.toISOString()),
        'phone_number': value.phoneNumber,
        'face_img': value.faceImg,
        'profile_img': value.profileImg,
        'shop_name': value.shopName,
        'machine_id': value.machineId,
        'shop_phone_number': value.shopPhoneNumber,
    };
}

