/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionItemRequest
 */
export interface TransactionItemRequest {
    /**
     * 
     * @type {number}
     * @memberof TransactionItemRequest
     */
    itemId: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionItemRequest
     */
    itemName?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionItemRequest
     */
    quantity: number;
}

/**
 * Check if a given object implements the TransactionItemRequest interface.
 */
export function instanceOfTransactionItemRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "itemId" in value;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function TransactionItemRequestFromJSON(json: any): TransactionItemRequest {
    return TransactionItemRequestFromJSONTyped(json, false);
}

export function TransactionItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionItemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'itemName': !exists(json, 'item_name') ? undefined : json['item_name'],
        'quantity': json['quantity'],
    };
}

export function TransactionItemRequestToJSON(value?: TransactionItemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_id': value.itemId,
        'item_name': value.itemName,
        'quantity': value.quantity,
    };
}

