/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionTopupRequest
 */
export interface TransactionTopupRequest {
    /**
     * 
     * @type {number}
     * @memberof TransactionTopupRequest
     */
    clientId: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionTopupRequest
     */
    totalTopup: number;
}

/**
 * Check if a given object implements the TransactionTopupRequest interface.
 */
export function instanceOfTransactionTopupRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "totalTopup" in value;

    return isInstance;
}

export function TransactionTopupRequestFromJSON(json: any): TransactionTopupRequest {
    return TransactionTopupRequestFromJSONTyped(json, false);
}

export function TransactionTopupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionTopupRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'totalTopup': json['total_topup'],
    };
}

export function TransactionTopupRequestToJSON(value?: TransactionTopupRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client_id': value.clientId,
        'total_topup': value.totalTopup,
    };
}

