/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TransactionItemRequest } from './TransactionItemRequest';
import {
    TransactionItemRequestFromJSON,
    TransactionItemRequestFromJSONTyped,
    TransactionItemRequestToJSON,
} from './TransactionItemRequest';

/**
 * 
 * @export
 * @interface WalletTransactionRequest
 */
export interface WalletTransactionRequest {
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionRequest
     */
    shopId: number;
    /**
     * 
     * @type {Array<TransactionItemRequest>}
     * @memberof WalletTransactionRequest
     */
    items: Array<TransactionItemRequest>;
    /**
     * 
     * @type {Array<string>}
     * @memberof WalletTransactionRequest
     */
    barcodes: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionRequest
     */
    clientId: number;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionRequest
     */
    transactionId: number;
}

/**
 * Check if a given object implements the WalletTransactionRequest interface.
 */
export function instanceOfWalletTransactionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "shopId" in value;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "barcodes" in value;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "transactionId" in value;

    return isInstance;
}

export function WalletTransactionRequestFromJSON(json: any): WalletTransactionRequest {
    return WalletTransactionRequestFromJSONTyped(json, false);
}

export function WalletTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletTransactionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shopId': json['shop_id'],
        'items': ((json['items'] as Array<any>).map(TransactionItemRequestFromJSON)),
        'barcodes': json['barcodes'],
        'clientId': json['client_id'],
        'transactionId': json['transaction_id'],
    };
}

export function WalletTransactionRequestToJSON(value?: WalletTransactionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shop_id': value.shopId,
        'items': ((value.items as Array<any>).map(TransactionItemRequestToJSON)),
        'barcodes': value.barcodes,
        'client_id': value.clientId,
        'transaction_id': value.transactionId,
    };
}

