"""initial

Revision ID: 8e5ef553a941
Revises: 
Create Date: 2023-03-15 14:38:56.005361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5ef553a941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auths_client_id'), 'auths', ['client_id'], unique=True)
    op.create_index(op.f('ix_auths_email'), 'auths', ['email'], unique=True)
    op.create_index(op.f('ix_auths_hashed_password'), 'auths', ['hashed_password'], unique=True)
    op.create_index(op.f('ix_auths_id'), 'auths', ['id'], unique=False)
    op.create_index(op.f('ix_auths_username'), 'auths', ['username'], unique=True)
    op.create_table('barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcodes_barcode'), 'barcodes', ['barcode'], unique=True)
    op.create_index(op.f('ix_barcodes_id'), 'barcodes', ['id'], unique=False)
    op.create_index(op.f('ix_barcodes_item_id'), 'barcodes', ['item_id'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('face_id', sa.Integer(), nullable=True),
    sa.Column('is_shop_owner', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_shop_id'), 'clients', ['shop_id'], unique=True)
    op.create_index(op.f('ix_clients_wallet_id'), 'clients', ['wallet_id'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_shop_id'), 'items', ['shop_id'], unique=True)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_machine_id'), 'shops', ['machine_id'], unique=True)
    op.create_index(op.f('ix_shops_owner_id'), 'shops', ['owner_id'], unique=True)
    op.create_index(op.f('ix_shops_stock_id'), 'shops', ['stock_id'], unique=True)
    op.create_index(op.f('ix_shops_wallet_id'), 'shops', ['wallet_id'], unique=True)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_item_id'), 'stocks', ['item_id'], unique=True)
    op.create_index(op.f('ix_stocks_shop_id'), 'stocks', ['shop_id'], unique=True)
    op.create_table('transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('is_barcode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_items_id'), 'transaction_items', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_items_item_id'), 'transaction_items', ['item_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_client_id'), 'transactions', ['client_id'], unique=True)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_shop_id'), 'transactions', ['shop_id'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('is_belong_to_shop', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_owner_id'), 'wallets', ['owner_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_owner_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_transactions_shop_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_client_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_transaction_items_item_id'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_id'), table_name='transaction_items')
    op.drop_table('transaction_items')
    op.drop_index(op.f('ix_stocks_shop_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_item_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_shops_wallet_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_stock_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_owner_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_machine_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_items_shop_id'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_clients_wallet_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_shop_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_barcodes_item_id'), table_name='barcodes')
    op.drop_index(op.f('ix_barcodes_id'), table_name='barcodes')
    op.drop_index(op.f('ix_barcodes_barcode'), table_name='barcodes')
    op.drop_table('barcodes')
    op.drop_index(op.f('ix_auths_username'), table_name='auths')
    op.drop_index(op.f('ix_auths_id'), table_name='auths')
    op.drop_index(op.f('ix_auths_hashed_password'), table_name='auths')
    op.drop_index(op.f('ix_auths_email'), table_name='auths')
    op.drop_index(op.f('ix_auths_client_id'), table_name='auths')
    op.drop_table('auths')
    # ### end Alembic commands ###
