"""migrate tables

Revision ID: 056ca507e85c
Revises: cf69303a24e2
Create Date: 2023-04-16 08:09:04.064699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056ca507e85c'
down_revision = 'cf69303a24e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
