"""migrate tables

Revision ID: 1663e1faab4c
Revises: e6b46432efae
Create Date: 2023-03-20 15:36:54.888836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1663e1faab4c'
down_revision = 'e6b46432efae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_face_ids', sa.Column('auth_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_face_ids', 'auths', ['auth_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_face_ids', type_='foreignkey')
    op.drop_column('client_face_ids', 'auth_id')
    # ### end Alembic commands ###
