"""migrate tables

Revision ID: 1f5d76ce38e9
Revises: 3a72a5119281
Create Date: 2023-04-20 00:00:06.356787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5d76ce38e9'
down_revision = '3a72a5119281'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
