"""migrate tables

Revision ID: 26555171a61f
Revises: 0cce10fa7bbd
Create Date: 2023-03-19 18:36:24.062398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26555171a61f'
down_revision = '0cce10fa7bbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payee_id', sa.String(), nullable=True),
    sa.Column('payee_account_number', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Time(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_transactions_id'), 'pending_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_transactions_id'), table_name='pending_transactions')
    op.drop_table('pending_transactions')
    # ### end Alembic commands ###
