"""migrate tables

Revision ID: 3a72a5119281
Revises: 7cd140e38364
Create Date: 2023-04-19 23:54:21.761571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a72a5119281'
down_revision = '7cd140e38364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
