"""migrate tables

Revision ID: 3b2feaddcf5c
Revises: 6d7573887c37
Create Date: 2023-03-15 19:01:07.969401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2feaddcf5c'
down_revision = '6d7573887c37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
