"""migrate tables

Revision ID: 42db2b0fb04b
Revises: bfefdf390165
Create Date: 2023-03-26 18:44:36.831949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42db2b0fb04b'
down_revision = 'bfefdf390165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
