"""migrate tables

Revision ID: 5008c8fe376c
Revises: a24e7e5b6906
Create Date: 2023-04-15 00:56:52.931398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5008c8fe376c'
down_revision = 'a24e7e5b6906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('shop_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'shop_name')
    # ### end Alembic commands ###
