"""migrate tables

Revision ID: 6530d311f8d6
Revises: 1663e1faab4c
Create Date: 2023-03-20 15:49:04.621683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6530d311f8d6'
down_revision = '1663e1faab4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
