"""migrate tables

Revision ID: 67e3dd0d70e1
Revises: 8e3bbd391c1b
Create Date: 2023-04-19 23:22:43.090991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e3dd0d70e1'
down_revision = '8e3bbd391c1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
