"""migrate tables

Revision ID: 6d7573887c37
Revises: 
Create Date: 2023-03-15 18:56:03.744816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7573887c37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_shop_owner', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('auths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auths_client_id'), 'auths', ['client_id'], unique=True)
    op.create_index(op.f('ix_auths_email'), 'auths', ['email'], unique=True)
    op.create_index(op.f('ix_auths_hashed_password'), 'auths', ['hashed_password'], unique=True)
    op.create_index(op.f('ix_auths_id'), 'auths', ['id'], unique=False)
    op.create_index(op.f('ix_auths_username'), 'auths', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auths_username'), table_name='auths')
    op.drop_index(op.f('ix_auths_id'), table_name='auths')
    op.drop_index(op.f('ix_auths_hashed_password'), table_name='auths')
    op.drop_index(op.f('ix_auths_email'), table_name='auths')
    op.drop_index(op.f('ix_auths_client_id'), table_name='auths')
    op.drop_table('auths')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
