"""migrate tables

Revision ID: 7079c8e154ac
Revises: ff989676527c
Create Date: 2023-03-17 00:45:00.975702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7079c8e154ac'
down_revision = 'ff989676527c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_items_item_id_fkey', 'transaction_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transaction_items_item_id_fkey', 'transaction_items', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
