"""migrate tables

Revision ID: 714a6a60ed59
Revises: 91b325cdcc52
Create Date: 2023-04-16 06:44:30.985798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714a6a60ed59'
down_revision = '91b325cdcc52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'client_wallets', 'auths', ['auth_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_wallets', type_='foreignkey')
    # ### end Alembic commands ###
