"""migrate tables

Revision ID: 7cd140e38364
Revises: 67e3dd0d70e1
Create Date: 2023-04-19 23:25:46.893464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd140e38364'
down_revision = '67e3dd0d70e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
