"""migrate tables

Revision ID: 7daf2e0f780f
Revises: b24423fa9f02
Create Date: 2023-04-13 17:08:53.055885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7daf2e0f780f'
down_revision = 'b24423fa9f02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topup_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashierless_account_number', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Time(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topup_transactions_id'), 'topup_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topup_transactions_id'), table_name='topup_transactions')
    op.drop_table('topup_transactions')
    # ### end Alembic commands ###
