"""migrate tables

Revision ID: 8e3bbd391c1b
Revises: 056ca507e85c
Create Date: 2023-04-16 08:10:06.413099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3bbd391c1b'
down_revision = '056ca507e85c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_wallets_auth_id_fkey', 'client_wallets', type_='foreignkey')
    op.drop_column('client_wallets', 'auth_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_wallets', sa.Column('auth_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_wallets_auth_id_fkey', 'client_wallets', 'auths', ['auth_id'], ['id'])
    # ### end Alembic commands ###
