"""migrate tables

Revision ID: 91b325cdcc52
Revises: fc4320d139ab
Create Date: 2023-04-16 06:32:10.314595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b325cdcc52'
down_revision = 'fc4320d139ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_wallets', sa.Column('auth_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_wallets', 'auth_id')
    # ### end Alembic commands ###
