"""migrate tables

Revision ID: 92a28a84f054
Revises: c043e328287f
Create Date: 2023-04-08 13:59:33.825892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a28a84f054'
down_revision = 'c043e328287f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
