"""migrate tables

Revision ID: 96a35926b70b
Revises: 7daf2e0f780f
Create Date: 2023-04-13 17:25:00.266282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a35926b70b'
down_revision = '7daf2e0f780f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topup_transactions', sa.Column('client_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topup_transactions', 'client_id')
    # ### end Alembic commands ###
