"""migrate tables

Revision ID: a24e7e5b6906
Revises: 96a35926b70b
Create Date: 2023-04-15 00:51:54.708605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24e7e5b6906'
down_revision = '96a35926b70b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
