"""migrate tables

Revision ID: a92d7cb4fd4f
Revises: 
Create Date: 2023-03-15 21:57:05.393959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92d7cb4fd4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_wallets_id'), 'client_wallets', ['id'], unique=False)
    op.create_table('shop_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_wallets_id'), 'shop_wallets', ['id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['shop_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_machine_id'), 'shops', ['machine_id'], unique=True)
    op.add_column('clients', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'client_wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'wallet_id')
    op.drop_index(op.f('ix_shops_machine_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_shop_wallets_id'), table_name='shop_wallets')
    op.drop_table('shop_wallets')
    op.drop_index(op.f('ix_client_wallets_id'), table_name='client_wallets')
    op.drop_table('client_wallets')
    # ### end Alembic commands ###
