"""migrate tables

Revision ID: b24423fa9f02
Revises: 92a28a84f054
Create Date: 2023-04-08 14:31:53.924112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24423fa9f02'
down_revision = '92a28a84f054'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
