"""migrate tables

Revision ID: bbfcb3a6c04f
Revises: ca8b46294567
Create Date: 2023-03-16 16:11:12.230067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfcb3a6c04f'
down_revision = 'ca8b46294567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
