"""migrate tables

Revision ID: be73497167d0
Revises: bbfcb3a6c04f
Create Date: 2023-03-16 16:35:27.711603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be73497167d0'
down_revision = 'bbfcb3a6c04f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
