"""migrate tables

Revision ID: bfefdf390165
Revises: 
Create Date: 2023-03-21 18:54:56.424964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfefdf390165'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_item_types_id'), 'item_types', ['id'], unique=False)
    op.create_foreign_key(None, 'items', 'item_types', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_item_types_id'), table_name='item_types')
    op.drop_table('item_types')
    # ### end Alembic commands ###
