"""migrate tables

Revision ID: c043e328287f
Revises: 42db2b0fb04b
Create Date: 2023-04-08 11:44:58.985835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c043e328287f'
down_revision = '42db2b0fb04b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
