"""migrate tables

Revision ID: ca8b46294567
Revises: fb35e70ee76e
Create Date: 2023-03-16 16:07:30.834057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8b46294567'
down_revision = 'fb35e70ee76e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
