"""migrate tables

Revision ID: cf69303a24e2
Revises: 714a6a60ed59
Create Date: 2023-04-16 07:11:07.105903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf69303a24e2'
down_revision = '714a6a60ed59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
