"""migrate tables

Revision ID: d8a314a9925b
Revises: f890c68004bc
Create Date: 2023-04-20 13:03:06.334560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a314a9925b'
down_revision = 'f890c68004bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_types', sa.Column('retail_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_types', 'retail_price')
    # ### end Alembic commands ###
