"""migrate tables

Revision ID: db9e3ce329ae
Revises: d8a314a9925b
Create Date: 2023-04-22 21:43:56.078244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9e3ce329ae'
down_revision = 'd8a314a9925b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'active')
    # ### end Alembic commands ###
