"""migrate tables

Revision ID: e6b46432efae
Revises: 26555171a61f
Create Date: 2023-03-20 14:07:21.669658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b46432efae'
down_revision = '26555171a61f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_face_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('face_encoded', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_face_ids_id'), 'client_face_ids', ['id'], unique=False)
    op.add_column('auths', sa.Column('face_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_auths_face_id'), 'auths', ['face_id'], unique=True)
    op.create_foreign_key(None, 'auths', 'client_face_ids', ['face_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auths', type_='foreignkey')
    op.drop_index(op.f('ix_auths_face_id'), table_name='auths')
    op.drop_column('auths', 'face_id')
    op.drop_index(op.f('ix_client_face_ids_id'), table_name='client_face_ids')
    op.drop_table('client_face_ids')
    # ### end Alembic commands ###
