"""migrate tables

Revision ID: f1c9a614ad53
Revises: 1f5d76ce38e9
Create Date: 2023-04-20 00:06:15.327579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c9a614ad53'
down_revision = '1f5d76ce38e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
