"""migrate tables

Revision ID: fb35e70ee76e
Revises: eea740d89785
Create Date: 2023-03-16 15:26:28.225437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb35e70ee76e'
down_revision = 'eea740d89785'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
