"""migrate tables

Revision ID: fba549ece4fc
Revises: 1937df64df47
Create Date: 2023-03-15 22:11:21.724725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba549ece4fc'
down_revision = '1937df64df47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
