"""migrate tables

Revision ID: fc4320d139ab
Revises: 9d6ef3d8a84b
Create Date: 2023-04-16 06:10:39.042140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4320d139ab'
down_revision = '9d6ef3d8a84b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
