"""migrate tables

Revision ID: ff989676527c
Revises: 0eda3a68d24b
Create Date: 2023-03-17 00:37:02.011958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff989676527c'
down_revision = '0eda3a68d24b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_items', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.drop_constraint('transaction_items_Transaction_id_fkey', 'transaction_items', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_items', 'transactions', ['transaction_id'], ['id'])
    op.drop_column('transaction_items', 'total_price')
    op.drop_column('transaction_items', 'Transaction_id')
    op.add_column('transactions', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('total_items', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'total_items')
    op.drop_column('transactions', 'total_price')
    op.add_column('transaction_items', sa.Column('Transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transaction_items', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction_items', type_='foreignkey')
    op.create_foreign_key('transaction_items_Transaction_id_fkey', 'transaction_items', 'transactions', ['Transaction_id'], ['id'])
    op.drop_column('transaction_items', 'transaction_id')
    # ### end Alembic commands ###
